# Generated by Django 5.0.2 on 2024-06-10 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_point_article_alter_point_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='average_points',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='article',
            name='count_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
